### PR TITLE
Fix force parameter and set last update when changing attributes

### LINKED ISSUE #210: Changing database attributes does not update mtime and cannot push
```
# ddb clone http://localhost:5000/admin/test
# cd test
# ddb chattr -public
# ddb push
Pushing to 'http://localhost:5000/admin/1'
Already up to date.
```

Which is not correct.

I also cannot force it:

```
ddb push --force
Pushing to 'http://localhost:5000/admin/1'
Already up to date.
```

### PR DESCRIPTION
**Pull request by HeDo88TH**
Fixes the behaviour of the `--force` parameter and adds the call to `setLastUpdate` when changing attributes.

Closes #210

### CODE REVIEW

File: src/cmd/chattr.cpp [hunk 1]
```diff
@@ -67,9 +67,23 @@ void Chattr::run(cxxopts::ParseResult& opts) {
             LOGD << "Setting attributes";
 
             if (attribute == "+public" || attribute == "+p") {
-                db->setPublic(true);
+
+                if (!db->isPublic()) {
+
+                    db->setPublic(true);
```
Comment (pierotofy) [inline src/cmd/chattr.cpp:73]: Logic should probably be moved inside `setPublic`.

Comment (HeDo88TH) [reply src/cmd/chattr.cpp]: Yes, it's cleaner 👍 https://github.com/DroneDB/DroneDB/pull/211/commits/7129d65985ed6b883584ef6d2c523581c12012d0

**Review by pierotofy — APPROVED** [review]

**Comment by pierotofy** [comment]
Looks good, thank you for the changes.
